# Render Infrastructure as Code
# https://docs.render.com/infrastructure-as-code

services:
  - type: web
    name: natural-highs
    runtime: node
    repo: https://github.com/wistb/Natural-Highs
    branch: main
    autoDeploy: true
    buildCommand: bun install && bun run build
    startCommand: bun .output/server/index.mjs
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production

previews:
  generation: automatic
  expireAfterDays: 7
